language: generic

notifications:
  email:
    recipients:
      - pierrick.roger@cea.fr

# For codecov (see https://github.com/codecov/example-bash)
sudo: required

# For codecov (see https://github.com/codecov/example-bash)
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

script:
  - make test

# For codecov (see https://github.com/codecov/example-bash)
after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage ./testthat.sh test &&
  bash <(curl -s https://codecov.io/bash)
